// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/MrSwed/go-musthave-shortener/internal/app/repository (interfaces: Repository)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/MrSwed/go-musthave-shortener/internal/app/domain"
	repository "github.com/MrSwed/go-musthave-shortener/internal/app/repository"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockRepository) GetAll(arg0 context.Context) (repository.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].(repository.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockRepositoryMockRecorder) GetAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockRepository)(nil).GetAll), arg0)
}

// GetFromShort mocks base method.
func (m *MockRepository) GetFromShort(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFromShort", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFromShort indicates an expected call of GetFromShort.
func (mr *MockRepositoryMockRecorder) GetFromShort(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFromShort", reflect.TypeOf((*MockRepository)(nil).GetFromShort), arg0, arg1)
}

// GetFromURL mocks base method.
func (m *MockRepository) GetFromURL(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFromURL", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFromURL indicates an expected call of GetFromURL.
func (mr *MockRepositoryMockRecorder) GetFromURL(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFromURL", reflect.TypeOf((*MockRepository)(nil).GetFromURL), arg0, arg1)
}

// NewShort mocks base method.
func (m *MockRepository) NewShort(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewShort", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewShort indicates an expected call of NewShort.
func (mr *MockRepositoryMockRecorder) NewShort(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewShort", reflect.TypeOf((*MockRepository)(nil).NewShort), arg0, arg1)
}

// NewShortBatch mocks base method.
func (m *MockRepository) NewShortBatch(arg0 context.Context, arg1 []domain.ShortBatchInputItem, arg2 string) ([]domain.ShortBatchResultItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewShortBatch", arg0, arg1, arg2)
	ret0, _ := ret[0].([]domain.ShortBatchResultItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewShortBatch indicates an expected call of NewShortBatch.
func (mr *MockRepositoryMockRecorder) NewShortBatch(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewShortBatch", reflect.TypeOf((*MockRepository)(nil).NewShortBatch), arg0, arg1, arg2)
}

// Restore mocks base method.
func (m *MockRepository) Restore() (repository.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore")
	ret0, _ := ret[0].(repository.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Restore indicates an expected call of Restore.
func (mr *MockRepositoryMockRecorder) Restore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockRepository)(nil).Restore))
}

// RestoreAll mocks base method.
func (m *MockRepository) RestoreAll(arg0 repository.Store) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreAll", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreAll indicates an expected call of RestoreAll.
func (mr *MockRepositoryMockRecorder) RestoreAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreAll", reflect.TypeOf((*MockRepository)(nil).RestoreAll), arg0)
}

// Save mocks base method.
func (m *MockRepository) Save(arg0 repository.Store) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRepositoryMockRecorder) Save(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepository)(nil).Save), arg0)
}
